const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, 'src', 'locales');

const newKeys = {
  en: {
    about: { title: "About Mocklingo AI", description: "Mocklingo AI is an Artificial Intelligence powered mock interview platform developed to help students and professionals prepare for technical and HR interviews. The system generates intelligent interview questions, converts speech into text, evaluates answers, and provides instant AI feedback to improve confidence and communication skills.", features_title: "Core Platform Features", f1_title: "AI Mock Interview Room", f1_desc: "Generates professional technical and situational interview questions matching your chosen domain using Google's Gemini AI.", f2_title: "Speech Recognition", f2_desc: "Converts your spoken answers directly into readable text in real-time using built-in browser Web Speech APIs.", f3_title: "Live Camera Preview", f3_desc: "Includes an overlay sandbox camera feed to help candidates monitor eye contact, posture, and facial expressions during practice.", f4_title: "Performance Analytics", f4_desc: "Computes detailed communication and technical confidence scores for each answer and tracks overall statistics across attempts.", f5_title: "Printable Assessment Report", f5_desc: "Generates detailed reports detailing specific strengths, communication flows, technical knowledge highlights, and downloadable PDF reports.", f6_title: "Modern Technology Stack", f6_desc: "Built on top of React, Vite, and Tailwind CSS v4 to deliver a lightning-fast, smooth, and lightweight single-page application experience." },
    rolesel: { title: "Select Designation", subtitle: "Choose the field you are interviewing for", continue_btn: "Continue" },
    dashboard: { welcome: "Welcome Back 👋", welcome_desc: "Track your interview performance, improve communication, boost confidence and prepare yourself for real-world technical interviews using Artificial Intelligence.", btn_interview: "Start Interview", btn_no_resume: "Interview Without Resume", stat1: "Interviews Completed", stat2: "Average Score", stat3: "Confidence", stat4: "Technical Skills", history_title: "Recent Interview History", clear_history: "Clear History", col_role: "Role", col_date: "Date", col_score: "Score", col_status: "Status", col_action: "Action", view_report: "View Report", no_interviews: "No interviews taken yet.", first_interview: "Take your first AI interview now", ai_performance: "AI Performance", confidence: "Confidence", communication: "Communication", technical: "Technical Skills", problem_solving: "Problem Solving", ai_recommendations: "AI Recommendations", tip1_title: "Practice Daily", tip1_desc: "Complete at least one AI interview every day to improve confidence and communication.", tip2_title: "Time Management", tip2_desc: "Keep your answers between one and two minutes for maximum interview impact.", tip3_title: "Technical Growth", tip3_desc: "Focus on Data Structures, Algorithms, JavaScript, React and System Design questions." }
  },
  de: {
    about: { title: "Über Mocklingo AI", description: "Mocklingo AI ist eine KI-gesteuerte Plattform für Testinterviews, die Studenten und Fachleute bei der Vorbereitung auf technische und HR-Interviews unterstützt.", features_title: "Hauptfunktionen", f1_title: "KI-Interviewraum", f1_desc: "Generiert professionelle Fragen für Ihre Domäne mit Google Gemini AI.", f2_title: "Spracherkennung", f2_desc: "Konvertiert Ihre gesprochenen Antworten in Echtzeit in Text.", f3_title: "Live-Kameraansicht", f3_desc: "Überwachen Sie Augenkontakt und Körperhaltung während der Übung.", f4_title: "Leistungsanalyse", f4_desc: "Berechnet Kommunikations- und technische Konfidenzpunkte.", f5_title: "Druckbarer Bericht", f5_desc: "Erstellt detaillierte Berichte mit Stärken und Schwächen.", f6_title: "Moderner Technologie-Stack", f6_desc: "Entwickelt mit React, Vite und Tailwind CSS v4." },
    rolesel: { title: "Rolle auswählen", subtitle: "Wählen Sie das Feld für Ihr Interview", continue_btn: "Weiter" },
    dashboard: { welcome: "Willkommen zurück 👋", welcome_desc: "Verfolgen Sie Ihre Interviewleistung und verbessern Sie sich mit künstlicher Intelligenz.", btn_interview: "Interview starten", btn_no_resume: "Interview ohne Lebenslauf", stat1: "Abgeschlossene Interviews", stat2: "Durchschnittliche Punktzahl", stat3: "Selbstvertrauen", stat4: "Technische Fähigkeiten", history_title: "Letzte Interview-Historie", clear_history: "Verlauf löschen", col_role: "Rolle", col_date: "Datum", col_score: "Punkte", col_status: "Status", col_action: "Aktion", view_report: "Bericht anzeigen", no_interviews: "Noch keine Interviews durchgeführt.", first_interview: "Jetzt Ihr erstes KI-Interview machen", ai_performance: "KI-Leistung", confidence: "Selbstvertrauen", communication: "Kommunikation", technical: "Technische Fähigkeiten", problem_solving: "Problemlösung", ai_recommendations: "KI-Empfehlungen", tip1_title: "Täglich üben", tip1_desc: "Führen Sie täglich mindestens ein KI-Interview durch.", tip2_title: "Zeitmanagement", tip2_desc: "Halten Sie Ihre Antworten zwischen einer und zwei Minuten.", tip3_title: "Technisches Wachstum", tip3_desc: "Konzentrieren Sie sich auf Datenstrukturen, Algorithmen und React." }
  },
  es: {
    about: { title: "Sobre Mocklingo AI", description: "Mocklingo AI es una plataforma de entrevistas simuladas con IA para estudiantes y profesionales.", features_title: "Características Principales", f1_title: "Sala de Entrevista IA", f1_desc: "Genera preguntas técnicas y situacionales con Google Gemini AI.", f2_title: "Reconocimiento de Voz", f2_desc: "Convierte sus respuestas habladas en texto en tiempo real.", f3_title: "Vista de Cámara en Vivo", f3_desc: "Monitoree el contacto visual y la postura durante la práctica.", f4_title: "Análisis de Rendimiento", f4_desc: "Calcula puntuaciones de comunicación y confianza técnica.", f5_title: "Informe Imprimible", f5_desc: "Genera informes detallados con fortalezas y debilidades.", f6_title: "Stack Tecnológico Moderno", f6_desc: "Construido con React, Vite y Tailwind CSS v4." },
    rolesel: { title: "Seleccionar Función", subtitle: "Elija el campo para su entrevista", continue_btn: "Continuar" },
    dashboard: { welcome: "Bienvenido de nuevo 👋", welcome_desc: "Realice un seguimiento de su rendimiento en entrevistas con Inteligencia Artificial.", btn_interview: "Iniciar Entrevista", btn_no_resume: "Entrevista Sin Currículum", stat1: "Entrevistas Completadas", stat2: "Puntuación Promedio", stat3: "Confianza", stat4: "Habilidades Técnicas", history_title: "Historial de Entrevistas", clear_history: "Borrar Historial", col_role: "Rol", col_date: "Fecha", col_score: "Puntuación", col_status: "Estado", col_action: "Acción", view_report: "Ver Informe", no_interviews: "No hay entrevistas todavía.", first_interview: "Haga su primera entrevista ahora", ai_performance: "Rendimiento IA", confidence: "Confianza", communication: "Comunicación", technical: "Habilidades Técnicas", problem_solving: "Resolución de Problemas", ai_recommendations: "Recomendaciones IA", tip1_title: "Practique a Diario", tip1_desc: "Complete al menos una entrevista IA cada día.", tip2_title: "Gestión del Tiempo", tip2_desc: "Mantenga sus respuestas entre uno y dos minutos.", tip3_title: "Crecimiento Técnico", tip3_desc: "Enfóquese en Estructuras de Datos, Algoritmos y React." }
  },
  fr: {
    about: { title: "À propos de Mocklingo AI", description: "Mocklingo AI est une plateforme d'entretiens simulés propulsée par l'IA pour aider étudiants et professionnels.", features_title: "Fonctionnalités Clés", f1_title: "Salle d'Entretien IA", f1_desc: "Génère des questions professionnelles avec Google Gemini AI.", f2_title: "Reconnaissance Vocale", f2_desc: "Convertit vos réponses orales en texte en temps réel.", f3_title: "Aperçu Caméra", f3_desc: "Surveillez le contact visuel et la posture pendant la pratique.", f4_title: "Analyse des Performances", f4_desc: "Calcule des scores de communication et de confiance technique.", f5_title: "Rapport Imprimable", f5_desc: "Génère des rapports détaillés avec forces et faiblesses.", f6_title: "Stack Technologique Moderne", f6_desc: "Construit avec React, Vite et Tailwind CSS v4." },
    rolesel: { title: "Sélectionner le Rôle", subtitle: "Choisissez le domaine de votre entretien", continue_btn: "Continuer" },
    dashboard: { welcome: "Bon retour 👋", welcome_desc: "Suivez vos performances d'entretien avec l'Intelligence Artificielle.", btn_interview: "Commencer l'Entretien", btn_no_resume: "Entretien Sans CV", stat1: "Entretiens Terminés", stat2: "Score Moyen", stat3: "Confiance", stat4: "Compétences Techniques", history_title: "Historique des Entretiens", clear_history: "Effacer l'Historique", col_role: "Rôle", col_date: "Date", col_score: "Score", col_status: "Statut", col_action: "Action", view_report: "Voir le Rapport", no_interviews: "Pas encore d'entretiens.", first_interview: "Passez votre premier entretien maintenant", ai_performance: "Performance IA", confidence: "Confiance", communication: "Communication", technical: "Compétences Techniques", problem_solving: "Résolution de Problèmes", ai_recommendations: "Recommandations IA", tip1_title: "Pratiquez Chaque Jour", tip1_desc: "Faites au moins un entretien IA par jour.", tip2_title: "Gestion du Temps", tip2_desc: "Gardez vos réponses entre une et deux minutes.", tip3_title: "Croissance Technique", tip3_desc: "Concentrez-vous sur les Structures de Données, Algorithmes et React." }
  },
  it: {
    about: { title: "Informazioni su Mocklingo AI", description: "Mocklingo AI è una piattaforma di simulazione di colloqui basata su IA per studenti e professionisti.", features_title: "Funzionalità Principali", f1_title: "Sala Colloquio IA", f1_desc: "Genera domande professionali con Google Gemini AI.", f2_title: "Riconoscimento Vocale", f2_desc: "Converte le risposte parlate in testo in tempo reale.", f3_title: "Anteprima Telecamera", f3_desc: "Monitora il contatto visivo e la postura durante la pratica.", f4_title: "Analisi delle Prestazioni", f4_desc: "Calcola punteggi di comunicazione e fiducia tecnica.", f5_title: "Rapporto Stampabile", f5_desc: "Genera rapporti dettagliati con punti di forza e debolezze.", f6_title: "Stack Tecnologico Moderno", f6_desc: "Costruito con React, Vite e Tailwind CSS v4." },
    rolesel: { title: "Seleziona Ruolo", subtitle: "Scegli il campo per il tuo colloquio", continue_btn: "Continua" },
    dashboard: { welcome: "Bentornato 👋", welcome_desc: "Monitora le tue prestazioni nei colloqui con l'Intelligenza Artificiale.", btn_interview: "Inizia Colloquio", btn_no_resume: "Colloquio Senza CV", stat1: "Colloqui Completati", stat2: "Punteggio Medio", stat3: "Fiducia", stat4: "Competenze Tecniche", history_title: "Cronologia Colloqui", clear_history: "Cancella Cronologia", col_role: "Ruolo", col_date: "Data", col_score: "Punteggio", col_status: "Stato", col_action: "Azione", view_report: "Vedi Rapporto", no_interviews: "Nessun colloquio ancora.", first_interview: "Fai il tuo primo colloquio ora", ai_performance: "Prestazione IA", confidence: "Fiducia", communication: "Comunicazione", technical: "Competenze Tecniche", problem_solving: "Problem Solving", ai_recommendations: "Raccomandazioni IA", tip1_title: "Esercitati Ogni Giorno", tip1_desc: "Completa almeno un colloquio IA al giorno.", tip2_title: "Gestione del Tempo", tip2_desc: "Mantieni le risposte tra uno e due minuti.", tip3_title: "Crescita Tecnica", tip3_desc: "Concentrati su Strutture Dati, Algoritmi e React." }
  },
  ja: {
    about: { title: "Mocklingo AIについて", description: "Mocklingo AIは、学生やプロフェッショナルが技術面接やHR面接に備えるためのAI模擬面接プラットフォームです。", features_title: "主な機能", f1_title: "AI面接ルーム", f1_desc: "Google Gemini AIを使用してプロフェッショナルな質問を生成します。", f2_title: "音声認識", f2_desc: "話した回答をリアルタイムでテキストに変換します。", f3_title: "ライブカメラプレビュー", f3_desc: "練習中に目線と姿勢をモニタリングします。", f4_title: "パフォーマンス分析", f4_desc: "コミュニケーションと技術的な自信スコアを計算します。", f5_title: "印刷可能なレポート", f5_desc: "強みと弱みを詳細にまとめたレポートを生成します。", f6_title: "モダンな技術スタック", f6_desc: "React、Vite、Tailwind CSS v4で構築。" },
    rolesel: { title: "職種を選択", subtitle: "面接するフィールドを選んでください", continue_btn: "続ける" },
    dashboard: { welcome: "おかえりなさい 👋", welcome_desc: "AIを使って面接パフォーマンスを追跡し、改善しましょう。", btn_interview: "面接を開始", btn_no_resume: "履歴書なしで面接", stat1: "面接完了数", stat2: "平均スコア", stat3: "自信", stat4: "技術スキル", history_title: "最近の面接履歴", clear_history: "履歴を消去", col_role: "役割", col_date: "日付", col_score: "スコア", col_status: "状態", col_action: "アクション", view_report: "レポートを見る", no_interviews: "まだ面接がありません。", first_interview: "最初のAI面接を今すぐ行う", ai_performance: "AIパフォーマンス", confidence: "自信", communication: "コミュニケーション", technical: "技術スキル", problem_solving: "問題解決", ai_recommendations: "AIの推奨事項", tip1_title: "毎日練習する", tip1_desc: "毎日少なくとも1つのAI面接を完了してください。", tip2_title: "時間管理", tip2_desc: "回答を1〜2分以内に収めてください。", tip3_title: "技術的成長", tip3_desc: "データ構造、アルゴリズム、ReactとSystem Designに集中しましょう。" }
  },
  ko: {
    about: { title: "Mocklingo AI 소개", description: "Mocklingo AI는 학생과 전문가가 기술 면접과 HR 면접을 준비할 수 있도록 설계된 AI 기반 모의 면접 플랫폼입니다.", features_title: "핵심 플랫폼 기능", f1_title: "AI 면접 룸", f1_desc: "Google Gemini AI를 사용하여 전문적인 질문을 생성합니다.", f2_title: "음성 인식", f2_desc: "말한 답변을 실시간으로 텍스트로 변환합니다.", f3_title: "라이브 카메라 미리보기", f3_desc: "연습 중 시선 및 자세를 모니터링합니다.", f4_title: "성능 분석", f4_desc: "커뮤니케이션 및 기술 신뢰도 점수를 계산합니다.", f5_title: "인쇄 가능한 보고서", f5_desc: "강점과 약점을 상세히 요약한 보고서를 생성합니다.", f6_title: "최신 기술 스택", f6_desc: "React, Vite, Tailwind CSS v4로 구축." },
    rolesel: { title: "직무 선택", subtitle: "면접할 분야를 선택하세요", continue_btn: "계속" },
    dashboard: { welcome: "다시 오셨군요 👋", welcome_desc: "AI를 사용하여 면접 성과를 추적하고 향상시키세요.", btn_interview: "면접 시작", btn_no_resume: "이력서 없이 면접", stat1: "완료된 면접", stat2: "평균 점수", stat3: "자신감", stat4: "기술 역량", history_title: "최근 면접 기록", clear_history: "기록 삭제", col_role: "역할", col_date: "날짜", col_score: "점수", col_status: "상태", col_action: "작업", view_report: "보고서 보기", no_interviews: "아직 면접이 없습니다.", first_interview: "첫 번째 AI 면접 시작하기", ai_performance: "AI 성과", confidence: "자신감", communication: "커뮤니케이션", technical: "기술 역량", problem_solving: "문제 해결", ai_recommendations: "AI 추천", tip1_title: "매일 연습하기", tip1_desc: "매일 최소 1번의 AI 면접을 완료하세요.", tip2_title: "시간 관리", tip2_desc: "답변을 1~2분 이내로 유지하세요.", tip3_title: "기술적 성장", tip3_desc: "자료구조, 알고리즘, React에 집중하세요." }
  },
  pt: {
    about: { title: "Sobre Mocklingo AI", description: "Mocklingo AI é uma plataforma de simulação de entrevistas com IA para estudantes e profissionais.", features_title: "Recursos Principais", f1_title: "Sala de Entrevista IA", f1_desc: "Gera perguntas profissionais com Google Gemini AI.", f2_title: "Reconhecimento de Voz", f2_desc: "Converte respostas faladas em texto em tempo real.", f3_title: "Visualização de Câmera ao Vivo", f3_desc: "Monitore o contato visual e postura durante a prática.", f4_title: "Análise de Desempenho", f4_desc: "Calcula pontuações de comunicação e confiança técnica.", f5_title: "Relatório Imprimível", f5_desc: "Gera relatórios detalhados com pontos fortes e fracos.", f6_title: "Stack Tecnológico Moderno", f6_desc: "Construído com React, Vite e Tailwind CSS v4." },
    rolesel: { title: "Selecionar Função", subtitle: "Escolha o campo para sua entrevista", continue_btn: "Continuar" },
    dashboard: { welcome: "Bem-vindo de volta 👋", welcome_desc: "Acompanhe seu desempenho em entrevistas com Inteligência Artificial.", btn_interview: "Iniciar Entrevista", btn_no_resume: "Entrevista Sem Currículo", stat1: "Entrevistas Concluídas", stat2: "Pontuação Média", stat3: "Confiança", stat4: "Habilidades Técnicas", history_title: "Histórico de Entrevistas", clear_history: "Limpar Histórico", col_role: "Função", col_date: "Data", col_score: "Pontuação", col_status: "Status", col_action: "Ação", view_report: "Ver Relatório", no_interviews: "Sem entrevistas ainda.", first_interview: "Faça sua primeira entrevista agora", ai_performance: "Desempenho IA", confidence: "Confiança", communication: "Comunicação", technical: "Habilidades Técnicas", problem_solving: "Resolução de Problemas", ai_recommendations: "Recomendações IA", tip1_title: "Pratique Diariamente", tip1_desc: "Conclua pelo menos uma entrevista IA por dia.", tip2_title: "Gestão do Tempo", tip2_desc: "Mantenha suas respostas entre um e dois minutos.", tip3_title: "Crescimento Técnico", tip3_desc: "Foque em Estruturas de Dados, Algoritmos e React." }
  },
  zh: {
    about: { title: "关于 Mocklingo AI", description: "Mocklingo AI 是一个由人工智能驱动的模拟面试平台，旨在帮助学生和专业人士准备技术和 HR 面试。", features_title: "核心平台功能", f1_title: "AI 面试室", f1_desc: "使用 Google Gemini AI 生成专业的面试问题。", f2_title: "语音识别", f2_desc: "实时将口语答案转换为文本。", f3_title: "实时摄像头预览", f3_desc: "在练习过程中监控眼神接触和姿势。", f4_title: "绩效分析", f4_desc: "计算沟通和技术置信度得分。", f5_title: "可打印的评估报告", f5_desc: "生成包含优缺点的详细报告。", f6_title: "现代技术栈", f6_desc: "使用 React、Vite 和 Tailwind CSS v4 构建。" },
    rolesel: { title: "选择职位", subtitle: "选择您面试的领域", continue_btn: "继续" },
    dashboard: { welcome: "欢迎回来 👋", welcome_desc: "利用人工智能跟踪您的面试表现并持续提升。", btn_interview: "开始面试", btn_no_resume: "无简历面试", stat1: "已完成面试", stat2: "平均分数", stat3: "自信心", stat4: "技术技能", history_title: "最近面试记录", clear_history: "清除记录", col_role: "角色", col_date: "日期", col_score: "分数", col_status: "状态", col_action: "操作", view_report: "查看报告", no_interviews: "还没有面试记录。", first_interview: "立即进行第一次 AI 面试", ai_performance: "AI 表现", confidence: "自信心", communication: "沟通能力", technical: "技术技能", problem_solving: "解决问题", ai_recommendations: "AI 建议", tip1_title: "每日练习", tip1_desc: "每天至少完成一次 AI 面试。", tip2_title: "时间管理", tip2_desc: "将回答控制在一到两分钟内。", tip3_title: "技术成长", tip3_desc: "专注于数据结构、算法、React 和系统设计。" }
  },
  ur: {
    about: { title: "Mocklingo AI کے بارے میں", description: "Mocklingo AI ایک اے آئی سے چلنے والا فرضی انٹرویو پلیٹ فارم ہے جو طلباء اور پیشہ ور افراد کو تکنیکی اور HR انٹرویوز کی تیاری میں مدد کرتا ہے۔", features_title: "بنیادی خصوصیات", f1_title: "اے آئی انٹرویو روم", f1_desc: "Google Gemini AI کا استعمال کرتے ہوئے پیشہ ورانہ سوالات بناتا ہے۔", f2_title: "آواز کی شناخت", f2_desc: "آپ کے بولے ہوئے جوابات کو فوری متن میں تبدیل کرتا ہے۔", f3_title: "لائیو کیمرہ پریویو", f3_desc: "مشق کے دوران آنکھ کا رابطہ اور وضع کی نگرانی کریں۔", f4_title: "کارکردگی کا تجزیہ", f4_desc: "مواصلاتی اور تکنیکی اعتماد کے اسکور کا حساب لگاتا ہے۔", f5_title: "قابل پرنٹ رپورٹ", f5_desc: "خوبیوں اور کمزوریوں کی تفصیل کے ساتھ رپورٹ تیار کرتا ہے۔", f6_title: "جدید ٹیکنالوجی اسٹیک", f6_desc: "React، Vite اور Tailwind CSS v4 کے ساتھ بنایا گیا۔" },
    rolesel: { title: "عہدہ منتخب کریں", subtitle: "انٹرویو کے لیے شعبہ منتخب کریں", continue_btn: "جاری رکھیں" },
    dashboard: { welcome: "واپس خوش آمدید 👋", welcome_desc: "مصنوعی ذہانت کے ساتھ اپنے انٹرویو کی کارکردگی کو ٹریک کریں اور بہتر بنائیں۔", btn_interview: "انٹرویو شروع کریں", btn_no_resume: "بغیر سی وی کے انٹرویو", stat1: "انٹرویوز مکمل ہوئے", stat2: "اوسط سکور", stat3: "اعتماد", stat4: "تکنیکی مہارتیں", history_title: "حالیہ انٹرویو کی تاریخ", clear_history: "تاریخ صاف کریں", col_role: "کردار", col_date: "تاریخ", col_score: "سکور", col_status: "حیثیت", col_action: "اقدام", view_report: "رپورٹ دیکھیں", no_interviews: "ابھی تک کوئی انٹرویو نہیں ہوا۔", first_interview: "ابھی اپنا پہلا اے آئی انٹرویو دیں", ai_performance: "اے آئی کارکردگی", confidence: "اعتماد", communication: "مواصلات", technical: "تکنیکی مہارتیں", problem_solving: "مسئلہ حل کرنا", ai_recommendations: "اے آئی کی سفارشات", tip1_title: "روزانہ مشق کریں", tip1_desc: "ہر روز کم از کم ایک اے آئی انٹرویو مکمل کریں۔", tip2_title: "وقت کا انتظام", tip2_desc: "اپنے جوابات ایک سے دو منٹ کے درمیان رکھیں۔", tip3_title: "تکنیکی ترقی", tip3_desc: "ڈیٹا اسٹرکچرز، الگورتھم اور React پر توجہ دیں۔" }
  }
};

const languages = Object.keys(newKeys);
languages.forEach(lang => {
  const filePath = path.join(localesDir, `${lang}.json`);
  const existing = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const merged = { ...existing, ...newKeys[lang] };
  fs.writeFileSync(filePath, JSON.stringify(merged, null, 2));
});
console.log("About, RoleSelection and Dashboard keys added!");
