const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');

// New keys to add per language
const newKeys = {
  en: {
    slider: { slide1_title: "Corporate Synergy", slide1_subtitle: "Building world-class teams.", slide2_title: "AI Evaluator", slide2_subtitle: "Instant, bias-free evaluations.", slide3_title: "Proven Success", slide3_subtitle: "Empowering both candidates and recruiters." },
    demo: { subtitle: "Interactive Sandbox", title: "Experience a Live AI Mock Interview Right Now", description: "No credit card required. Experience how our assessment module records audio, translates speech to text, and uses Google Gemini to grade communication and technical competency immediately.", step1_title: "Select Job Role", step1_desc: "Pick a role and generate professional questions.", step2_title: "Speak Your Response", step2_desc: "Use your microphone to record. Browser API translates speech live.", step3_title: "Review Detailed Insights", step3_desc: "Analyze grades, strengths, weaknesses, and key actions.", choose_domain: "Choose Your Job Domain", choose_domain_desc: "The AI interviewer will formulate technical and situational questions matching this specific domain.", generate_btn: "Generate AI Question", loading_question: "Gemini AI formulating technical question...", your_response: "Your Response Answer", words: "words", placeholder: "Type your response here or click the mic button below to record your voice...", stop_recording: "Stop Recording", speak_response: "Speak Response", evaluate_btn: "Evaluate Response", eval_generated: "Evaluation Generated", eval_processed: "Feedback processed successfully", overall_score: "OVERALL SCORE", strengths: "Strengths", weaknesses: "Flaws & Weaknesses", improvement: "Improvement Steps", practice_again: "Practice Again" }
  },
  de: {
    slider: { slide1_title: "Unternehmenssynergie", slide1_subtitle: "Weltklasse-Teams aufbauen.", slide2_title: "KI-Evaluator", slide2_subtitle: "Sofortige, vorurteilsfreie Bewertungen.", slide3_title: "Bewiesener Erfolg", slide3_subtitle: "Kandidaten und Recruiter stärken." },
    demo: { subtitle: "Interaktive Sandbox", title: "Erleben Sie jetzt ein Live-KI-Interview", description: "Keine Kreditkarte erforderlich. Erleben Sie, wie unser Modul Audio aufzeichnet und mit Google Gemini bewertet.", step1_title: "Jobrolle auswählen", step1_desc: "Wählen Sie eine Rolle aus.", step2_title: "Antwort sprechen", step2_desc: "Nutzen Sie Ihr Mikrofon.", step3_title: "Detaillierte Einblicke überprüfen", step3_desc: "Noten, Stärken und Schwächen analysieren.", choose_domain: "Wählen Sie Ihre Jobrolle", choose_domain_desc: "Der KI-Interviewer wird Fragen passend zu Ihrer Rolle formulieren.", generate_btn: "KI-Frage generieren", loading_question: "Gemini KI formuliert Frage...", your_response: "Ihre Antwort", words: "Wörter", placeholder: "Tippen Sie hier oder klicken Sie auf das Mikrofon...", stop_recording: "Aufnahme stoppen", speak_response: "Antwort sprechen", evaluate_btn: "Antwort bewerten", eval_generated: "Bewertung erstellt", eval_processed: "Feedback erfolgreich verarbeitet", overall_score: "GESAMTERGEBNIS", strengths: "Stärken", weaknesses: "Schwächen", improvement: "Verbesserungsschritte", practice_again: "Nochmal üben" }
  },
  es: {
    slider: { slide1_title: "Sinergia Corporativa", slide1_subtitle: "Construyendo equipos de clase mundial.", slide2_title: "Evaluador de IA", slide2_subtitle: "Evaluaciones instantáneas y sin sesgos.", slide3_title: "Éxito Comprobado", slide3_subtitle: "Empoderando candidatos y reclutadores." },
    demo: { subtitle: "Sandbox Interactivo", title: "Experimente una Entrevista en Vivo Ahora", description: "Sin tarjeta de crédito. Experimente cómo grabamos audio y calificamos con Gemini.", step1_title: "Seleccionar Rol", step1_desc: "Elija un rol y genere preguntas.", step2_title: "Hable su Respuesta", step2_desc: "Use su micrófono para grabar.", step3_title: "Revisar Perspectivas", step3_desc: "Analice notas, fortalezas y debilidades.", choose_domain: "Elija su Dominio", choose_domain_desc: "El entrevistador IA formulará preguntas adecuadas.", generate_btn: "Generar Pregunta IA", loading_question: "Gemini IA formulando pregunta...", your_response: "Su Respuesta", words: "palabras", placeholder: "Escriba aquí o haga clic en el micrófono...", stop_recording: "Detener Grabación", speak_response: "Hablar Respuesta", evaluate_btn: "Evaluar Respuesta", eval_generated: "Evaluación Generada", eval_processed: "Feedback procesado con éxito", overall_score: "PUNTUACIÓN TOTAL", strengths: "Fortalezas", weaknesses: "Debilidades", improvement: "Pasos de Mejora", practice_again: "Practicar de Nuevo" }
  },
  fr: {
    slider: { slide1_title: "Synergie d'Entreprise", slide1_subtitle: "Construire des équipes de classe mondiale.", slide2_title: "Évaluateur IA", slide2_subtitle: "Évaluations immédiates et sans biais.", slide3_title: "Succès Prouvé", slide3_subtitle: "Autonomiser candidats et recruteurs." },
    demo: { subtitle: "Bac à Sable Interactif", title: "Vivez une Interview IA en Direct Maintenant", description: "Sans carte de crédit. Voyez comment notre module enregistre et note avec Gemini.", step1_title: "Sélectionner le Rôle", step1_desc: "Choisissez un rôle et générez des questions.", step2_title: "Parler votre Réponse", step2_desc: "Utilisez votre microphone.", step3_title: "Examiner les Détails", step3_desc: "Analysez les notes, forces et faiblesses.", choose_domain: "Choisissez votre Domaine", choose_domain_desc: "L'intervieweur IA formulera des questions adaptées.", generate_btn: "Générer une Question IA", loading_question: "Gemini IA formule une question...", your_response: "Votre Réponse", words: "mots", placeholder: "Tapez ici ou cliquez sur le micro...", stop_recording: "Arrêter l'Enregistrement", speak_response: "Parler la Réponse", evaluate_btn: "Évaluer la Réponse", eval_generated: "Évaluation Générée", eval_processed: "Feedback traité avec succès", overall_score: "SCORE GLOBAL", strengths: "Forces", weaknesses: "Faiblesses", improvement: "Étapes d'Amélioration", practice_again: "Pratiquer Encore" }
  },
  it: {
    slider: { slide1_title: "Sinergia Aziendale", slide1_subtitle: "Costruire team di livello mondiale.", slide2_title: "Valutatore IA", slide2_subtitle: "Valutazioni istantanee e imparziali.", slide3_title: "Successo Dimostrato", slide3_subtitle: "Potenziare candidati e recruiter." },
    demo: { subtitle: "Sandbox Interattivo", title: "Vivi un'Intervista IA dal Vivo Ora", description: "Nessuna carta di credito. Scopri come il modulo registra e valuta con Gemini.", step1_title: "Seleziona Ruolo", step1_desc: "Scegli un ruolo e genera domande.", step2_title: "Parla la tua Risposta", step2_desc: "Usa il tuo microfono.", step3_title: "Esamina i Dettagli", step3_desc: "Analizza voti, punti di forza e debolezze.", choose_domain: "Scegli il tuo Dominio", choose_domain_desc: "L'intervistatore IA formulerà domande appropriate.", generate_btn: "Genera Domanda IA", loading_question: "Gemini IA formula una domanda...", your_response: "La tua Risposta", words: "parole", placeholder: "Digita qui o clicca sul microfono...", stop_recording: "Ferma Registrazione", speak_response: "Parla Risposta", evaluate_btn: "Valuta Risposta", eval_generated: "Valutazione Generata", eval_processed: "Feedback elaborato con successo", overall_score: "PUNTEGGIO TOTALE", strengths: "Punti di Forza", weaknesses: "Punti Deboli", improvement: "Passi di Miglioramento", practice_again: "Esercitati Ancora" }
  },
  ja: {
    slider: { slide1_title: "企業の相乗効果", slide1_subtitle: "世界クラスのチームを構築。", slide2_title: "AI評価者", slide2_subtitle: "即時の公平な評価。", slide3_title: "実証された成功", slide3_subtitle: "候補者と採用担当者をサポート。" },
    demo: { subtitle: "インタラクティブサンドボックス", title: "今すぐライブAI面接を体験", description: "クレジットカード不要。音声を録音し、Geminiで評価する方法を体験してください。", step1_title: "職種を選択", step1_desc: "職種を選び、質問を生成します。", step2_title: "回答を話す", step2_desc: "マイクを使用して録音します。", step3_title: "詳細なインサイトを確認", step3_desc: "成績、強み、弱みを分析します。", choose_domain: "職種を選択", choose_domain_desc: "AIインタビュアーがドメインに合わせた質問をします。", generate_btn: "AI質問を生成", loading_question: "Gemini AIが質問を作成中...", your_response: "あなたの回答", words: "語", placeholder: "ここに入力するか、マイクをクリックしてください...", stop_recording: "録音を停止", speak_response: "回答を話す", evaluate_btn: "回答を評価", eval_generated: "評価が完了しました", eval_processed: "フィードバックが正常に処理されました", overall_score: "総合スコア", strengths: "強み", weaknesses: "弱点", improvement: "改善ステップ", practice_again: "もう一度練習" }
  },
  ko: {
    slider: { slide1_title: "기업 시너지", slide1_subtitle: "세계적 수준의 팀 구축.", slide2_title: "AI 평가자", slide2_subtitle: "즉각적이고 공정한 평가.", slide3_title: "검증된 성공", slide3_subtitle: "지원자와 채용 담당자 지원." },
    demo: { subtitle: "인터랙티브 샌드박스", title: "지금 바로 라이브 AI 면접 체험", description: "신용카드 없이도 됩니다. 오디오 녹음과 Gemini 평가를 경험해 보세요.", step1_title: "직무 선택", step1_desc: "직무를 선택하고 질문을 생성하세요.", step2_title: "응답 말하기", step2_desc: "마이크를 사용하여 녹음하세요.", step3_title: "상세 인사이트 검토", step3_desc: "점수, 강점, 약점을 분석하세요.", choose_domain: "직무 도메인 선택", choose_domain_desc: "AI 면접관이 적합한 질문을 구성합니다.", generate_btn: "AI 질문 생성", loading_question: "Gemini AI가 질문을 구성 중...", your_response: "귀하의 답변", words: "단어", placeholder: "여기에 입력하거나 마이크를 클릭하세요...", stop_recording: "녹음 중지", speak_response: "응답 말하기", evaluate_btn: "응답 평가", eval_generated: "평가 완료", eval_processed: "피드백이 성공적으로 처리되었습니다", overall_score: "총 점수", strengths: "강점", weaknesses: "약점", improvement: "개선 단계", practice_again: "다시 연습" }
  },
  pt: {
    slider: { slide1_title: "Sinergia Corporativa", slide1_subtitle: "Construindo equipes de classe mundial.", slide2_title: "Avaliador de IA", slide2_subtitle: "Avaliações instantâneas e imparciais.", slide3_title: "Sucesso Comprovado", slide3_subtitle: "Fortalecendo candidatos e recrutadores." },
    demo: { subtitle: "Sandbox Interativo", title: "Experimente uma Entrevista com IA Agora", description: "Sem cartão de crédito. Veja como gravamos e avaliamos com Gemini.", step1_title: "Selecionar Função", step1_desc: "Escolha uma função e gere perguntas.", step2_title: "Fale sua Resposta", step2_desc: "Use seu microfone para gravar.", step3_title: "Revisar Insights", step3_desc: "Analise notas, pontos fortes e fracos.", choose_domain: "Escolha seu Domínio", choose_domain_desc: "O entrevistador IA formulará perguntas adequadas.", generate_btn: "Gerar Pergunta IA", loading_question: "Gemini IA formulando pergunta...", your_response: "Sua Resposta", words: "palavras", placeholder: "Digite aqui ou clique no microfone...", stop_recording: "Parar Gravação", speak_response: "Falar Resposta", evaluate_btn: "Avaliar Resposta", eval_generated: "Avaliação Gerada", eval_processed: "Feedback processado com sucesso", overall_score: "PONTUAÇÃO TOTAL", strengths: "Pontos Fortes", weaknesses: "Pontos Fracos", improvement: "Passos de Melhoria", practice_again: "Praticar Novamente" }
  },
  zh: {
    slider: { slide1_title: "企业协同", slide1_subtitle: "打造世界级团队。", slide2_title: "AI 评估员", slide2_subtitle: "即时、无偏见的评估。", slide3_title: "经实证的成功", slide3_subtitle: "赋能候选人和招聘人员。" },
    demo: { subtitle: "交互式沙盒", title: "立即体验 AI 模拟面试", description: "无需信用卡。体验音频录制和 Gemini 评分的全过程。", step1_title: "选择职位", step1_desc: "选择职位并生成专业问题。", step2_title: "说出您的回答", step2_desc: "使用麦克风录音。", step3_title: "查看详细见解", step3_desc: "分析成绩、优点和缺点。", choose_domain: "选择您的职业领域", choose_domain_desc: "AI 面试官将制定适合您领域的问题。", generate_btn: "生成 AI 问题", loading_question: "Gemini AI 正在制定问题...", your_response: "您的回答", words: "字", placeholder: "在此输入或点击麦克风按钮...", stop_recording: "停止录音", speak_response: "说出回答", evaluate_btn: "评估回答", eval_generated: "评估已生成", eval_processed: "反馈处理成功", overall_score: "总分", strengths: "优点", weaknesses: "缺点与弱点", improvement: "改进步骤", practice_again: "再次练习" }
  },
  ur: {
    slider: { slide1_title: "کارپوریٹ ہم آہنگی", slide1_subtitle: "عالمی سطح کی ٹیمیں بنانا۔", slide2_title: "اے آئی جانچنے والا", slide2_subtitle: "فوری، غیر جانبدارانہ جائزے۔", slide3_title: "ثابت شدہ کامیابی", slide3_subtitle: "امیدواروں اور بھرتی کرنے والوں کو بااختیار بنانا۔" },
    demo: { subtitle: "انٹرایکٹو سینڈ باکس", title: "ابھی لائیو اے آئی انٹرویو تجربہ کریں", description: "کسی کریڈٹ کارڈ کی ضرورت نہیں۔ دیکھیں کہ کس طرح ہم آواز ریکارڈ کرتے ہیں اور Gemini سے گریڈ دیتے ہیں۔", step1_title: "کردار منتخب کریں", step1_desc: "ایک کردار منتخب کریں اور سوالات بنائیں۔", step2_title: "اپنا جواب بولیں", step2_desc: "ریکارڈ کرنے کے لیے مائیکروفون استعمال کریں۔", step3_title: "تفصیلی بصیرت دیکھیں", step3_desc: "گریڈز، خوبیاں اور کمزوریاں تجزیہ کریں۔", choose_domain: "اپنا ڈومین منتخب کریں", choose_domain_desc: "اے آئی انٹرویوئر آپ کے ڈومین کے مطابق سوالات بنائے گا۔", generate_btn: "اے آئی سوال بنائیں", loading_question: "Gemini AI سوال بنا رہا ہے...", your_response: "آپ کا جواب", words: "الفاظ", placeholder: "یہاں ٹائپ کریں یا مائیکروفون پر کلک کریں...", stop_recording: "ریکارڈنگ روکیں", speak_response: "جواب بولیں", evaluate_btn: "جواب کا جائزہ لیں", eval_generated: "جائزہ تیار ہو گیا", eval_processed: "فیڈ بیک کامیابی سے پروسیس ہوا", overall_score: "مجموعی سکور", strengths: "خوبیاں", weaknesses: "خامیاں", improvement: "بہتری کے اقدامات", practice_again: "دوبارہ مشق کریں" }
  }
};

const languages = Object.keys(newKeys);

languages.forEach(lang => {
  const filePath = path.join(localesDir, `${lang}.json`);
  const existing = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const merged = { ...existing, ...newKeys[lang] };
  fs.writeFileSync(filePath, JSON.stringify(merged, null, 2));
});

console.log("All locale files updated with demo and slider keys!");
